services:
  - type: web
    plan: free
    name: tts_learmax
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "fastapi run --workers 4 main.py"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4